import BilingualPresentation, { PresentationData, Visual } from "./BilingualPresentation";

const r = "/project-assets/reports/";
const visual = (src: string, fa: string, en: string, source: string): Visual => ({ src, title: { fa, en }, source });

const data: PresentationData = {
  part: "PART 2",
  eyebrow: { fa: "مهندسی ویژگی و تحلیل رضایت", en: "Feature engineering and satisfaction" },
  title: { fa: "رضایت از گارانتی در متن", en: "Warranty satisfaction in language" },
  subtitle: { fa: "ساخت امتیاز پیوسته با Word2Vec و شباهت معنایی", en: "A continuous score built with Word2Vec semantics" },
  description: { fa: "در بخش دوم، نقدهای مرتبط با گارانتی جدا شدند و با واژه‌های مرجع مثبت و منفی، یک امتیاز رضایت معنایی برای هر متن ساخته شد.", en: "Part 2 isolates warranty-related reviews and derives a semantic satisfaction score using positive and negative reference terms." },
  metrics: [
    { value: "1 → 5", title: { fa: "بازه امتیاز رضایت", en: "Satisfaction range" }, detail: { fa: "نگاشت امتیاز معنایی به مقیاس قابل‌تفسیر", en: "Semantic scores mapped to an interpretable scale" } },
    { value: "Word2Vec", title: { fa: "نمایش واژه‌ها", en: "Word representation" }, detail: { fa: "استفاده از شباهت برداری واژه‌های متن", en: "Vector similarity between review terms" } },
    { value: "2 poles", title: { fa: "قطب‌های معنایی", en: "Semantic poles" }, detail: { fa: "واژه‌های مرجع مثبت و منفی", en: "Positive and negative reference vocabularies" } },
    { value: "5.0", title: { fa: "قله اصلی توزیع", en: "Main distribution peak" }, detail: { fa: "تمرکز بالای متن‌های رضایت‌محور", en: "A strong concentration of satisfied reviews" } }
  ],
  findings: [
    { title: { fa: "فیلتر موضوعی", en: "Topic filtering" }, text: { fa: "فقط متن‌هایی که درباره warranty و مفاهیم نزدیک بودند وارد محاسبه شدند.", en: "Only reviews discussing warranty and related concepts entered the scoring stage." } },
    { title: { fa: "امتیاز پیوسته", en: "Continuous score" }, text: { fa: "فاصله متن از قطب مثبت و منفی به یک مقدار پیوسته تبدیل شد؛ بنابراین نتیجه فقط یک برچسب دودویی نیست.", en: "Distance from positive and negative semantic poles becomes a continuous value rather than a binary label." } },
    { title: { fa: "هم‌راستا با امتیاز کاربران", en: "Aligned with user ratings" }, text: { fa: "انباشت امتیازهای رضایت بالا با گرایش مثبت داده خام سازگار است.", en: "The concentration of high satisfaction scores is consistent with the raw dataset’s positive skew." } }
  ],
  tables: [
    { title:{fa:"واژه‌های نزدیک به warranty",en:"Terms closest to warranty"}, description:{fa:"خروجی شباهت Word2Vec برای پیدا کردن شکل‌های نوشتاری و مفاهیم نزدیک.",en:"Word2Vec similarity output capturing spelling variants and related concepts."}, columns:[{fa:"واژه",en:"Term"},{fa:"شباهت",en:"Similarity"}], rows:[["warrantee","0.9220"],["warrenty","0.9072"],["warranties","0.8617"],["warantee","0.7605"],["warrantied","0.7511"],["squaretrade","0.7124"],["guarantee","0.7011"]], source:"Satisfaction-level-7.ipynb · cells 7–8" },
    { title:{fa:"نمونه خروجی رضایت",en:"Sample satisfaction output"}, description:{fa:"نمونه‌ای از نگاشت محصول به امتیاز رضایت گارانتی.",en:"A sample of product-level warranty satisfaction scores."}, columns:[{fa:"ASIN",en:"ASIN"},{fa:"رضایت",en:"Satisfaction"}], rows:[["0545105668","5.0"],["140053271X","5.0"],["1495443043","5.0"],["6541654530","1.0"],["9565727689","3.0"],["9573212919","1.0"]], source:"Satisfaction-level-7.ipynb · cell 12" }
  ],
  groups: [{ title: { fa: "توزیع رضایت گارانتی", en: "Warranty satisfaction distribution" }, description: { fa: "نسخه نهایی و خواناتر نمودار تولیدشده در notebook بخش دوم.", en: "The final, presentation-ready chart generated by the Part 2 notebook." }, visuals: [
    visual(r + "Distribution%20of%20Warranty%20Satisfaction%20Scores.png", "توزیع نهایی امتیاز رضایت", "Final warranty satisfaction distribution", "reports · generated by part2/Satisfaction-level-7.ipynb")
  ] }],
  takeaway: { fa: "بخش دوم متن بدون‌ساختار را به یک ویژگی عددی قابل‌تفسیر تبدیل کرد؛ ویژگی‌ای که شدت رضایت از خدمات گارانتی را نشان می‌دهد.", en: "Part 2 turns unstructured language into an interpretable numeric feature that captures the intensity of warranty satisfaction." }
};

export default function PreparationPresentation() { return <BilingualPresentation data={data} />; }
